const games = [
  {
    title: "Super Squishy Candy Console",
    date: "2024-12-01",
    collaboration: "Bloody",
    image: "./games/images/2024_super_squishy.gif",
    short_desc: "It's christmas and you find this strange console under the tree.",
    details: "A game made for Goldensun, during the Secret santa jam 2024.",
    url_label: "Download",
    url: "https://drive.google.com/file/d/1pOqIAWmYEhRungu67GUmsYFrDekJLvQB/view?usp=sharing",
  },
  {
    title: "Chakana (Chapter 1)",
    date: "2024-10-01",
    collaboration: "Bloody",
    image: "./games/images/2024_chakana.gif",
    short_desc: "An ordinary date takes a dark turn",
    details: "You planned for a quiet evening. The table is set, the atmosphere is warm, and the night seems to be unfolding just as you'd hoped. But as the meal progresses, something feels off. In this atmospheric horror game, explore your home as strange events disrupt your date, leaving you to navigate through questions, confrontations, and your own dread. Each decision can bring you closer to unraveling the mystery or plunge you deeper into its grip. The time is running out, manage the eerie silence, and tread carefully to keep your secrets hidden—or risk exposing yourself. Face a twisting psychological horror that questions how far you'd go to protect yourself from your fate.",
    url_label: "View Page",
    url: "https://tiz010.itch.io/chakana-chapter-1",
  },
  {
    title: "Farming Simulator But with guns",
    date: "2024-01-31",
    collaboration: "Karim",
    image: "./games/images/2024_farming_simulator_but_with_guns.png",
    short_desc: "A farming simulator with a surprising twist",
    details: "A farming simulator with a surprising twist",
    url_label: "View Page",
    url: "https://globalgamejam.org/games/2024/farming-simulator-guns-9"
  },
  {
    title: "Pigments",
    date: "2023-12-20",
    collaboration: "Bloody",
    image: "./games/images/2023_pigments.gif",
    short_desc: "Uncover the secrets of an alien world.",
    details: "Explore eerie landscapes, awakening memories and forming an enigmatic connection with your surroundings. With no text, the controls and story seamlessly reveal themselves as you delve into this mysterious puzzle platformer",
    url_label: "View Page",
    url: "https://tiz010.itch.io/pigments",
  },
  {
    title: "Christmas Combo",
    date: "2022-12-29",
    collaboration: "Bloody",
    image: "./games/images/2022_christmas_combo.gif",
    short_desc: "Hit all the targets with a single shot, sliding on the ice.",
    details: "Hit all the targets with a single shot, sliding on the ice.",
    url_label: "Download",
    url: "https://drive.google.com/file/d/18Rs1QGI6kJ3QaKbvV8R1NSvhrDnQarLX/view?usp=sharing"
  },
  {
    title: "CaveBox",
    date: "2022-11-13",
    collaboration: "Bloody",
    image: "./games/images/2022_cavebox.webp",
    short_desc: "Text game about mysterious caves filled with challenges and secrets.",
    details: "Text game about mysterious caves filled with challenges and secrets.",
    url_label: "View Page",
    url: "https://tiz010.itch.io/cavebox",
  },
  {
    title: "Herikoputa",
    date: "2022-05-01",
    collaboration: "Erry",
    jam: "Competizione GMI",
    image: "./games/images/2022_herikoputa.png",
    short_desc: "Launch yourself with your friends through a dangerous path, armed with torpedos",
    details: "Launch yourself with your friends through a dangerous path, armed with torpedos",
    url_label: "Download",
    url: "https://drive.google.com/file/d/1FgjlpxVTMG_aWAW11puFHEDBdnaalHdM/view",
  },
  {
    title: "Mirror Layers",
    date: "2021-10-30",
    collaboration: "Mad, Erry, Lod",
    image: "./games/images/2021_mirror_layers.jpg",
    short_desc: "Mirror Layers is a first person social horror game. Cooperate with other players to solve challenging puzzles. Explore and collaborate to unravel the mystery behind Apartment 12 and its horrific and distorted mirror reality.",
    details: "Mirror Layers is a first person social horror game. Cooperate with other players to solve challenging puzzles. Explore and collaborate to unravel the mystery behind Apartment 12 and its horrific and distorted mirror reality.",
    url_label: "View Page",
    url: "https://store.steampowered.com/app/1490980/Mirror_Layers/",
  },
  {
    title: "Mirror Layers Prologue",
    date: "2021-09-17",
    collaboration: "Mad, Erry, Lod",
    image: "./games/images/2021_mirror_layers_prologue.webp",
    short_desc: "This prologue will give you only a glimpse of what you'll find in Mirror Layers.",
    details: "This prologue will give you only a glimpse of what you'll find in Mirror Layers.",
    url_label: "View Page",
    url: "https://mymadnessworks.itch.io/mirrorlayers-escaperoom",
  },
  {
    title: "Blink",
    date: "2021-11-26",
    collaboration: "SerpensSolida, Ballman",
    jam: "Terrorottobre",
    image: "./games/images/2021_blink.jpg",
    short_desc: "You are going to visit someone at the local graveyard, what could possibly go wrong?",
    details: "You are going to visit someone at the local graveyard, what could possibly go wrong?",
    url_label: "View Page",
    url: "https://gamejolt.com/games/blink/550462",
  },
  {
    title: "A Day",
    date: "2021-02-04",
    collaboration: "Hyper, Mad",
    image: "./games/images/2021_a_day.jpg",
    short_desc: "In A Day you'll be able to control 8 different characters in a 2D side-scrolling open map: give them life by chaining their actions, rewind the time and reach for the highest score possible! This day is yours to make!",
    details: "In A Day you'll be able to control 8 different characters in a 2D side-scrolling open map: give them life by chaining their actions, rewind the time and reach for the highest score possible! This day is yours to make!",
    url_label: "View Page",
    url: "https://store.steampowered.com/app/1507990/A_Day__to_bring_them_happiness",
  },
  {
    title: "A Day To bring them happiness",
    date: "2020-11-22",
    jam: "startup cities gamejam",
    collaboration: "Hyper, Mad",
    image: "./games/images/2021_a_day_to_bring.png",
    short_desc: "Made for the Global Startupcities Gamejam with the theme 'A Win-win situation'",
    details: "Made for the Global Startupcities Gamejam with the theme 'A Win-win situation'",
    url_label: "View Page",
    url: "https://mymadnessworks.itch.io/a-day",
  },
  {
    title: "Surroundead",
    date: "2020-10-03",
    collaboration: "Erry, Lod",
    image: "./games/images/2020_surroundead.png",
    short_desc: "Amongus photo-realistic clone. Made in unity as a test for a multiplayer library.",
    details: "Amongus clone but photo-realistic. Made in unity as a test for a multiplayer library.",
    url_label: "Download",
    url: "https://drive.google.com/file/d/1ZoHndvuNSzjjpsdg7WWacyoD_2_Di9MW/view?usp=sharing"
  },
  {
    title: "Crop Nights",
    date: "2020-06-10",
    collaboration: "",
    image: "./games/images/2020_crop_nights.png",
    short_desc: "Those plants have something peculiar about them.",
    details: "Those plants have something peculiar about them.",
    url_label: "Play on Browser",
    url: "https://gx.games/games/lbqayi/crop-nights/"
  },
  {
    title: "The Alley",
    date: "2020-05-03",
    jam: "Competizione GMI",
    image: "./games/images/2020_the_alley.webp",
    short_desc: "You wake up in a structure, under observation. Stay away from the restricted zone.",
    details: "The alley is a 3D card game made for the GMI competition.",
    url_label: "View Page",
    url: "https://tiz010.itch.io/thealley",
  },
  {
    title: "Atmospair",
    date: "2020-02-04",
    jam: "Global game jam 2020 - Tema 'Repair'",
    collaboration: "Cla, Lod, SerpensSolida, Pietro Prebianca, Nadeea",
    image: "./games/images/2020_atmospair.png",
    short_desc: "A game about fixing natural disasters. You have multiple weapons: some will solve them, other will make things worse.",
    details: "A game about fixing natural disasters. You have multiple weapons: some will solve them, other will make things worse. Find out which ones handle what situations and lower the air pollution bar by putting out fires and planting trees. Only when it reaches zero you'll rapair earth and save it. Be careful though, if the pollution gets too much high, the earth will ne destroyed and you'll lose. Will you be able to master this fast-paced game?",
    url_label: "View Page",
    url: "https://v3.globalgamejam.org/2020/games/atmospair-2",
  },
  {
    title: "Everybody's Home",
    date: "2019-01-01",
    collaboration: "GMI (Mad, Doom, Cla, Ball, Jak, Lod, etc)",
    jam: "Global game jam 2019 - Tema 'Casa'",
    image: "./games/images/2019_everybodys_home.png",
    short_desc: "For me 'home' means robots that attack you",
    details: "For me 'home' means robots that attack you"
  },
  {
    title: "Frog Feast",
    date: "2018-02-04",
    collaboration: "Mad",
    image: "./games/images/2018_frog_feast.png",
    short_desc: "Made in 1 hour for the 1 hour game jam",
    details: "Couch battle game wher you have to push your friend",
    url_label: "Download",
    url: "https://drive.google.com/file/d/1qZ4QvJ0IPGWZTESX85dp5kv6WEyYiGxj/view",
  },
  {
    title: "Biotransphere",
    date: "2018-01-31",
    collaboration: "Pietro, WhySere, Chiara Giannangeli, Haze_93, redPurpose",
    jam: "Global game jam 2018",
    image: "./games/images/2018_biotransphere.png",
    short_desc: "After many failed attempts to save our Planet, the scientific community has started the BioTranSphere Protocol",
    details: "After many failed attempts to save our Planet, the scientific community has started the BioTranSphere Protocol, to save the decimated population and all other species from the brink of extinction... Use your Gun to transfer between objects, physical properties such as Temperature, Weight, and Light. Absorb with RMB Convey with LMB Interactions: Temperature: Fire, Cauldron Weight: Mobile Crates Light: Luminous Sphere, Lamps",
    url_label: "View Page",
    url:"https://v3.globalgamejam.org/2018/games/biotransphere",
  },
  {
    title: "Mirror Layers (Asylum Jam)",
    date: "2016-11-14",
    collaboration: "Erry, Virgil, Lod, Soufian Addioui, (other Virgil's friend)",
    image: "./games/images/2016_mirror_layers.png",
    short_desc: "We ask you only to give us a part of you: Part of your identity.",
    details: "We ask you only to give us a part of you: Part of your identity.",
    url_label: "View Page",
    url: "https://gamejolt.com/games/mirrorlayers/208588",
  },
  {
    title: "Flappy Fish",
    date: "2016-06-08",
    collaboration: "Lod",
    image: "./games/images/2016_flappy_fish.png",
    short_desc: "Flappy bird clone under the sea",
    details: "Flappy bird clone under the sea",
  },
  {
    title: "Tainted",
    date: "2014-08-27",
    collaboration: "Mad, Lod",
    jam: "ludum dare 30",
    image: "./games/images/2014_tainted.png",
    short_desc: "This game is NOT MEANT to be played with TeamSpeak or other chat/vocal chat systems.",
    details: "This game is NOT MEANT to be played with TeamSpeak or other chat/vocal chat systems.",
    url_label: "View Page",
    url: "https://gamejolt.com/games/tainted/33307",
  },
  {
    title: "Undead Pixels",
    date: "2014-02-10",
    collaboration: "Lod",
    image: "./games/images/2014_undead_pixels.jpg",
    short_desc: "Survive zombie hordes in this retro-inspired pixel art game for Android.",
    details: "Survive zombie hordes in this retro-inspired pixel art game for Android.",
    url_label: "View Page",
    url: "https://play.google.com/store/apps/details?id=com.revolab.UndeadPixels",
  },
  {
    title: "Calm Time",
    date: "2013-11-22",
    collaboration: "Mad, Virgil, Lod",
    image: "./games/images/2013_calm_time.png",
    short_desc: "The chirping of the sparrows and the breath of the wind is my sole company.",
    details: "The chirping of the sparrows and the breath of the wind is my sole company.",
    url: "https://gamejolt.com/games/calm-time/19354",
  },
  {
    title: "7 Days",
    date: "2013-05-14",
    collaboration: "Lod",
    image: "./games/images/2013_7days.png",
    short_desc: "Find out what is going on in the strange house where you just woke up",
    details: "Find out what is going on in the strange house where you just woke up",
    url_label: "View Page",
    url: "https://gamejolt.com/games/7days/14592"
  },
  {
    title: "Airte",
    date: "2012-10-02",
    jam: "Horror GMI",
    image: "./games/images/2012_airte.png",
    short_desc: "A soul named Airte. Once a metalhead, now seeking faith in the afterlife.",
    details: "A lost soul named Airte, once a devoted metalhead, had a revelation on his deathbed—he must put his faith in Jesus Christ. But in the afterlife, The Diaulo seeks to drag him back to his old ways, forcing him to listen to a haunting song that commands worship of 'Satan, infinite trinity.' Yet, Jesus 3 has granted Airte a divine gift: The Light Weapon. With his radiant white companion by his side and bare feet upon holy ground, Airte must purge the demonic forces emerging from the accursed walls. The goal? Absorb the light emitted by tormented souls. Collect 1,000, and Airte will finally find his redemption. Controls: WASD + Mouse",
    url_label: "Download",
    url: "https://tizsoft.altervista.org/Airte/Airte.zip"
  },
  {
    title: "Connect 4",
    date: "2012-08-03",
    collaboration: "Lod",
    image: "./games/images/2012_connect4.png",
    short_desc: "A classic game of Connect 4. Online multiplayer",
    details: "A classic game of Connect 4. Online multiplayer",
    url_label: "Download",
    url: "https://tizsoft.altervista.org/connect4/ConnectDG_1_2.zip",
  },
  {
    title: "Solitair Worm",
    date: "2012-04-18",
    image: "./games/images/2012_solitair_worm.png",
    short_desc: "A game about a giant worm that eats everything in its path",
    details: "A game about a giant worm that eats everything in its path",
    url_label: "Download",
  },
  {
    title: "Tetris 3D Online Tournament",
    date: "2011-03-11",
    image: "./games/images/2011_tetris.png",
    short_desc: "A simple 3D Tetris game with online leaderboards",
    details: "A simple 3D Tetris game with online leaderboards.",
    url_label: "View Page",
    url: "http://www.tizsoft.altervista.org/tetris",
  },
  {
    title: "Transporter",
    date: "2011-02-08",
    image: "./games/images/2011_transporter.png",
    short_desc: "My first released game. A simple physics-based puzzle platformer",
    details: "My first released game. A simple physics-based puzzle platformer",
    url_label: "Download",
    url: "https://drive.google.com/file/d/1boLizy6ljq7i3Qz2KE-nsEgmIbPLPKMV/view?usp=sharing",
  }
];
